# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: HashUtils(with .NET8)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Show Program Infos
      run: |
        echo "==================当前使用的.NET版本=================="
        dotnet --version
        echo "==================当前目录信息=================="
        echo "当前目录: "`pwd`


    - name: Build&Publish ConsoleApp1
      run: |
        cd ./HashUtils/ConsoleApp1
        echo "当前目录: "`pwd`
        dotnet restore
        dotnet build --no-restore
        dotnet clean
        dotnet publish /p:Configuration=Release /p:PublishProfile=NET8-winx64

    - name: Build&Publish ConsoleApp2
      run: |
        cd ./HashUtils/ConsoleApp2
        echo "当前目录: "`pwd`
        dotnet restore
        dotnet build --no-restore
        dotnet clean
        dotnet publish /p:Configuration=Release /p:PublishProfile=NET8-winx64

    - name: Build&Publish ConsoleApp3
      run: |
        cd ./HashUtils/ConsoleApp3
        echo "当前目录: "`pwd`
        dotnet restore
        dotnet build --no-restore
        dotnet clean
        dotnet publish /p:Configuration=Release /p:PublishProfile=AnyCPU-winx64-依赖框架
        dotnet publish /p:Configuration=Release /p:PublishProfile=AnyCPU-winx64-独立
        dotnet publish /p:Configuration=Release /p:PublishProfile=x64-winx64-依赖框架
        dotnet publish /p:Configuration=Release /p:PublishProfile=x64-winx64-独立

    - name: Upload Publish Result Files
      uses: actions/upload-artifact@main
      with:
        name: HashUtils
        path: ./HashUtils/ConsoleApp3/bin/Release
